//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

@class NSArray;

@interface GTMSessionFetcherLogViewController : UITableViewController
{
    NSArray *logsFolderURLs_;
    _Bool opensScrolledToEnd_;
    CDUnknownBlockType callbackBlock_;
}

+ (id)controllerWithTarget:(id)arg1 selector:(SEL)arg2;
@property(copy, nonatomic) CDUnknownBlockType callbackBlock; // @synthesize callbackBlock=callbackBlock_;
- (void).cxx_destruct;
- (void)doneButtonClicked:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)shortenedNameForURL:(id)arg1;
- (void)setOpensScrolledToEnd:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithStyle:(long long)arg1;

@end

