//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIWebViewDelegate.h"

@class NSString, NSURL;

@interface GTMSessionFetcherLoggingWebViewController : UIViewController <UIWebViewDelegate>
{
    _Bool opensScrolledToEnd_;
    NSURL *htmlURL_;
}

- (void).cxx_destruct;
- (void)webViewDidFinishLoad:(id)arg1;
- (id)webView;
- (void)didTapBackButton:(id)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithURL:(id)arg1 title:(id)arg2 opensScrolledToEnd:(_Bool)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

