//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTMOAuth2Authentication, GTMSessionFetcherService, NSString;

@interface NIAIosAuthenticationManager : NSObject
{
    GTMOAuth2Authentication *_auth;
    NSString *_clientAuthToken;
    GTMSessionFetcherService *_fetcherService;
}

- (void).cxx_destruct;
- (id)userEmail;
- (id)description;
- (void)getAccountOrLogin:(id)arg1 clientSecret:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)navigationController;
- (void)clearAuth;
- (id)defaultSourceString;
- (void)refreshIdTokenWithCompletion:(CDUnknownBlockType)arg1;
- (id)init;

@end

