//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CBCentralManagerDelegate.h"
#import "CBPeripheralDelegate.h"

@class CBCentralManager, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface PGPBluetoothDriver : NSObject <CBCentralManagerDelegate, CBPeripheralDelegate>
{
    _Bool _poweredOn;
    NSMutableDictionary *_startCallbacks;
    NSMutableDictionary *_namesToScan;
    NSMutableDictionary *_connectingPeripherals;
    NSMutableDictionary *_discoveryPeripherals;
    NSMutableDictionary *_characteristicCallbacks;
    NSMutableDictionary *_valueChangeCallbacks;
    NSMutableDictionary *_writeCallbacks;
    NSMutableDictionary *_readCallbacks;
    CBCentralManager *_centralManager;
    NSObject<OS_dispatch_queue> *_centralManagerQueue;
}

@property _Bool poweredOn; // @synthesize poweredOn=_poweredOn;
@property(retain) NSObject<OS_dispatch_queue> *centralManagerQueue; // @synthesize centralManagerQueue=_centralManagerQueue;
@property(retain) CBCentralManager *centralManager; // @synthesize centralManager=_centralManager;
@property(retain) NSMutableDictionary *readCallbacks; // @synthesize readCallbacks=_readCallbacks;
@property(retain) NSMutableDictionary *writeCallbacks; // @synthesize writeCallbacks=_writeCallbacks;
@property(retain) NSMutableDictionary *valueChangeCallbacks; // @synthesize valueChangeCallbacks=_valueChangeCallbacks;
@property(retain) NSMutableDictionary *characteristicCallbacks; // @synthesize characteristicCallbacks=_characteristicCallbacks;
@property(retain) NSMutableDictionary *discoveryPeripherals; // @synthesize discoveryPeripherals=_discoveryPeripherals;
@property(retain) NSMutableDictionary *connectingPeripherals; // @synthesize connectingPeripherals=_connectingPeripherals;
@property(retain) NSMutableDictionary *namesToScan; // @synthesize namesToScan=_namesToScan;
@property(retain) NSMutableDictionary *startCallbacks; // @synthesize startCallbacks=_startCallbacks;
- (void).cxx_destruct;
- (void)readValueForCharacteristic:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)peripheral:(id)arg1 didWriteValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)writeData:(id)arg1 forCharacteristic:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateNotificationStateForCharacteristic:(id)arg2 error:(id)arg3;
- (void)enableValueChangeNotification:(_Bool)arg1 forCharacteristic:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)discoverCharacteristicsForService:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)peripheral:(id)arg1 didDiscoverServices:(id)arg2;
- (void)discoverServices:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)centralManager:(id)arg1 didDisconnectPeripheral:(id)arg2 error:(id)arg3;
- (void)disconnectPeripheral:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)centralManager:(id)arg1 didFailToConnectPeripheral:(id)arg2 error:(id)arg3;
- (void)centralManager:(id)arg1 didConnectPeripheral:(id)arg2;
- (void)connectPeripheral:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)centralManager:(id)arg1 didDiscoverPeripheral:(id)arg2 advertisementData:(id)arg3 RSSI:(id)arg4;
- (void)stopScanningPeripheralNamed:(id)arg1;
- (_Bool)startScanningPeripheralNamed:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)centralManagerDidUpdateState:(id)arg1;
- (void)stopTag:(int)arg1;
- (void)startTag:(int)arg1 completion:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) _Bool isScanning;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

